base_model: Qwen/Qwen3-1.7B-Base

# Automatically upload checkpoint and final model to HF
hub_model_id: mikeriess/Qwen3-1.7B-Base-FineWeb2-dk

load_in_8bit: false
load_in_4bit: false
strict: false

max_steps: 150000
pretraining_dataset:
  - name: dan_Latn
    path: HuggingFaceFW/fineweb-2
    split: train
    type: pretrain

sequence_len: 8192
sample_packing: true
eval_sample_packing: true

plugins:
  # axolotl.integrations.cut_cross_entropy.CutCrossEntropyPlugin
  - axolotl.integrations.liger.LigerPlugin
liger_rope: true
liger_rms_norm: true
liger_glu_activation: true
liger_fused_linear_cross_entropy: true

# adapter: qlora
# lora_model_dir:
# lora_r: 32
# lora_alpha: 64
# lora_dropout: 0.05
# lora_target_linear: true

wandb_project: qwen3-pretraining
wandb_entity:
wandb_watch:
wandb_name: telenor_syv_qwen3-1.7b-fineweb-2-dk
wandb_log_model:

gradient_accumulation_steps: 1
micro_batch_size: 1048 #256
num_epochs: 1
optimizer: adamw_torch_fused
lr_scheduler: cosine
learning_rate: 0.0002

bf16: auto
tf32: true

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
resume_from_checkpoint:
logging_steps: 1
flash_attention: true

warmup_ratio: 0.1
evals_per_epoch: 4
saves_per_epoch: 1
weight_decay: 0.0
fsdp:
  - full_shard
  - auto_wrap
fsdp_config:
  fsdp_limit_all_gathers: true
  fsdp_sync_module_states: true
  fsdp_offload_params: true
  fsdp_use_orig_params: false
  fsdp_cpu_ram_efficient_loading: true
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_transformer_layer_cls_to_wrap: Qwen3DecoderLayer
  fsdp_state_dict_type: FULL_STATE_DICT
  fsdp_sharding_strategy: FULL_SHARD
special_tokens:

# save_first_step: true  # uncomment this to validate checkpoint saving works with your config