base_model: Qwen/Qwen3-1.7B-Base

auto_resume_from_checkpoints: true

max_steps: 150000
pretraining_dataset:
  - name: dan_Latn
    path: HuggingFaceFW/fineweb-2
    split: train
    type: pretrain
    skip: 2723499


plugins:
  # axolotl.integrations.cut_cross_entropy.CutCrossEntropyPlugin
  - axolotl.integrations.liger.LigerPlugin
liger_rope: true
liger_rms_norm: true
liger_glu_activation: true
liger_fused_linear_cross_entropy: true

strict: false


val_set_size: 0.0
output_dir: ./outputs/out
dataset_prepared_path: last_run_prepared

sequence_len: 8192
sample_packing: true
eval_sample_packing: false
pad_to_sequence_len: true


wandb_project: qwen3-pretraining
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 8

optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

bf16: auto
tf32: true

gradient_checkpointing: offload
gradient_checkpointing_kwargs:
  use_reentrant: false
logging_steps: 1
flash_attention: true

warmup_steps: 20
evals_per_epoch: 50
saves_per_epoch: 50
weight_decay: 0.0
special_tokens: