base_model: Qwen/Qwen3-8B-Base

auto_resume_from_checkpoints: true

max_steps: 150000
pretraining_dataset:
  - name: dan_Latn
    path: HuggingFaceFW/fineweb-2
    split: train
    type: pretrain

load_in_8bit: false
load_in_4bit: false
strict: false

plugins:
  - axolotl.integrations.liger.LigerPlugin

liger_rope: true
liger_rms_norm: true
liger_glu_activation: true
liger_layer_norm: true
liger_fused_linear_cross_entropy: true

output_dir: ./outputs/out

sequence_len: 8192
sample_packing: true
flex_attention: true


flex_attn_compile_kwargs:
  dynamic: false
  mode: max-autotune-no-cudagraphs


wandb_project: qwen3-pretraining
wandb_entity:
wandb_watch:
wandb_name: Telenor_Syv_qwen3-1.7b-fineweb-2-100k
wandb_log_model:

gradient_accumulation_steps: 8
micro_batch_size: 8
max_steps: 150000
optimizer: adamw_torch_fused
lr_scheduler: cosine
learning_rate: 2e-5

bf16: true
tf32: true

resume_from_checkpoint:
logging_steps: 1

# evals_per_epoch: 50
saves_per_epoch: 50

warmup_ratio: 0.1
weight_decay: 0.0
fsdp:
  - full_shard
  - auto_wrap

fsdp_config:
  fsdp_version: 2
  fsdp_offload_params: false
  fsdp_cpu_ram_efficient_loading: true
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_transformer_layer_cls_to_wrap: Qwen3DecoderLayer
  fsdp_state_dict_type: FULL_STATE_DICT
  fsdp_sharding_strategy: FULL_SHARD
  fsdp_reshard_after_forward: true
  fsdp_activation_checkpointing: true

special_tokens:

# save_first_step: true  # uncomment this to validate checkpoint saving works with your config